name: .Net Framework CI-CD

on:
  push:
    branches: master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Create Build Directory
      run: mkdir _build
      
    - name: Restore Packages
      run: nuget restore aspnet-get-started.sln

    - name: Build Solution
      run: |
        msbuild.exe aspnet-get-started.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Buldle
        path: "./_build"        
        
    - name: Login to Azure
      uses: azure/login@v2
      with:
          client-id: ${{ vars.CLIENT_ID }}
          tenant-id: ${{ vars.TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION_ID }}  
    
    - name: WebApp Settings
      uses: azure/appservice-settings@v1
      with:
        app-name: aspnet-get-started20240524140807
        mask-inputs: false
        # slot-name: 'staging'  # Optional and needed only if the settings have to be configured on the specific deployment slot
        # app-settings-json: '[{ "name": "soemthing", "value": "1", "slotSetting": false }]'
        connection-strings-json: '${{ secrets.CONNECTION_STRINGS }}'

    - name: Publish Artifacts to Azure
      uses: Azure/webapps-deploy@v3
      with:
        app-name: aspnet-get-started20240524140807
        package: "./_build"
        slot-name: production        
